// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using artesania.Database;

#nullable disable

namespace artesania.Migrations
{
    [DbContext(typeof(ArtesaniaContext))]
    [Migration("20240522013023_moreTables")]
    partial class moreTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("artesania.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Expiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("artesania.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hecho de piezas de cuero en piezas originales",
                            ImageURL = "https://th.bing.com/th/id/R.e3c2b536ba1a86a7e03559c765a9bd13?rik=roz00SogitUCDg&pid=ImgRaw&r=0",
                            Name = "Bolso de cuero",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pulsera hecha de Tagua, también conocida como 'marfil vegetal'.",
                            ImageURL = "https://main.globalmarketmanager.com/images/1/pt2p.jpg",
                            Name = "Pulsera de Tagua",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Reconocidos por su larga y cuidadosa elaboracion.",
                            ImageURL = "https://www.lavanguardia.com/files/og_thumbnail/uploads/2015/02/20/5fa2787324dfc.jpeg",
                            Name = "Sombrero de paja Toquilla",
                            Price = 75m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Manta tejida a mano en la región de Otavalo.",
                            ImageURL = "https://th.bing.com/th/id/OIP.qbpXCKvF9rZzYmgFfGXMHwHaE_?rs=1&pid=ImgDetMain",
                            Name = "Manta de Otavalo",
                            Price = 25m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Zapatos de cuero hechos a mano en Cotacachi.",
                            ImageURL = "https://www.somosmamas.com.ar/wp-content/uploads/2019/06/product-hugerect-1958297-126370-1520514051-61c3ea2fb41ad97118ff5a48525211d6.jpg",
                            Name = "Zapatos de Cuero de Cotacachi",
                            Price = 90m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cerámica pintada a mano de la ciudad de Cuenca.",
                            ImageURL = "https://www.vistazo.com/binrepository/640x524/0c0/0d0/none/12727/OUUQ/foto-3-calidad-ceramica-artesa-2_416590_20220503103626.jpg",
                            Name = "Cerámica de Cuenca",
                            Price = 30m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Chal tejido con lana de alpaca.",
                            ImageURL = "https://i.etsystatic.com/17835651/r/il/1b599f/2749386384/il_fullxfull.2749386384_lsqe.jpg",
                            Name = "Chal de Alpaca",
                            Price = 25m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Máscara tradicional utilizada en la fiesta de la Diabluma.",
                            ImageURL = "https://i.pinimg.com/originals/42/4e/25/424e2521e7fc2cef080b5c97e965ed62.jpg",
                            Name = "Máscara de Diabluma",
                            Price = 20m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Hamaca tejida a mano en la provincia de Manabí.",
                            ImageURL = "https://i.pinimg.com/originals/f6/66/99/f66699085122d24e0b3f5534c01ee23a.jpg",
                            Name = "Hamaca de Manabí",
                            Price = 15m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Talla de madera hecha a mano en el pueblo de San Antonio.",
                            ImageURL = "https://www.expectativa.ec/wp-content/uploads/2020/09/w4LQATAm04HkMLu.jpg",
                            Name = "Talla de Madera de San Antonio",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("artesania.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("artesania.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("artesania.Entities.Purchase", b =>
                {
                    b.HasOne("artesania.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("artesania.Entities.ShoppingCart", b =>
                {
                    b.HasOne("artesania.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artesania.Entities.Purchase", null)
                        .WithMany("Products")
                        .HasForeignKey("PurchaseId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("artesania.Entities.Purchase", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
